version: '3.9'
services:
  db:
    image: mysql:8
    container_name: el-db
    restart: always
    environment:
      MYSQL_DATABASE: el
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - '3306:3306'
